version: "3.2"
services:
    db:
      image: mysql:5.7
      volumes:
        - db_data2:/var/lib/mysql
        - ./mysql-dump:/docker-entrypoint-initdb.d
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: password
        MYSQL_DATABASE: hh
        MYSQL_USER: root
        MYSQL_PASSWORD: password

      ports:
        - 3307:3306
    app:
      depends_on:
        - db
      build: ./
      command: npm start
      volumes:
        - ./:/var/www/app 
      ports:
        - 3001:3000

volumes:
    db_data: {}